apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-rl-agent-config
  namespace: trading-system
  labels:
    app: trading-rl-agent
data:
  config.yaml: |
    environment: production
    debug: false
    log_level: INFO

    # Data pipeline configuration
    data:
      symbols: ["AAPL", "GOOGL", "MSFT", "TSLA", "AMZN", "NVDA", "META", "NFLX"]
      start_date: "2023-01-01"
      end_date: "2024-01-01"
      timeframe: "1h"
      source: "yfinance"
      refresh_interval: 300  # 5 minutes
      batch_size: 1000
      parallel_workers: 4

    # Trading execution configuration
    execution:
      paper_trading: true
      max_position: 0.05
      stop_loss: 0.02
      take_profit: 0.05
      update_interval: 5
      max_concurrent_trades: 10
      risk_per_trade: 0.01
      max_daily_loss: 0.05

    # Model training configuration
    training:
      epochs: 200
      batch_size: 64
      learning_rate: 0.0005
      device: "cuda"
      workers: 4
      validation_split: 0.2
      early_stopping_patience: 10
      model_checkpoint_interval: 10

    # Backtesting configuration
    backtesting:
      initial_capital: 100000
      commission: 0.001
      slippage: 0.0001
      benchmark: "SPY"
      confidence_level: 0.95

    # API configuration
    api:
      host: "0.0.0.0"
      port: 8000
      workers: 4
      timeout: 30
      rate_limit: 1000
      cors_origins: ["*"]

    # Monitoring configuration
    monitoring:
      metrics_port: 9090
      health_check_interval: 30
      alert_thresholds:
        memory_usage: 0.8
        cpu_usage: 0.8
        error_rate: 0.05
        latency_p95: 1000

    # Database configuration
    database:
      type: "postgresql"
      host: "trading-db-service"
      port: 5432
      name: "trading_system"
      pool_size: 10
      max_overflow: 20

    # Cache configuration
    cache:
      type: "redis"
      host: "trading-redis-service"
      port: 6379
      db: 0
      ttl: 3600

    # Message queue configuration
    queue:
      type: "rabbitmq"
      host: "trading-rabbitmq-service"
      port: 5672
      username: "trading_user"
      vhost: "trading"

  # Service-specific configurations
  api-config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8000
      workers: 4
      timeout: 30
      max_requests: 1000
      max_requests_jitter: 100

    cors:
      origins: ["*"]
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      headers: ["*"]

    rate_limiting:
      enabled: true
      requests_per_minute: 1000
      burst_size: 100

  trading-engine-config.yaml: |
    engine:
      update_interval: 5
      max_concurrent_trades: 10
      risk_management:
        max_position_size: 0.05
        stop_loss: 0.02
        take_profit: 0.05
        max_daily_loss: 0.05

    execution:
      paper_trading: true
      commission: 0.001
      slippage: 0.0001
      min_order_size: 100
      max_order_size: 10000

    monitoring:
      metrics_interval: 60
      alert_thresholds:
        drawdown: 0.1
        consecutive_losses: 5
        error_rate: 0.05

  data-pipeline-config.yaml: |
    pipeline:
      batch_size: 1000
      parallel_workers: 4
      refresh_interval: 300
      retry_attempts: 3
      retry_delay: 60

    sources:
      yfinance:
        enabled: true
        rate_limit: 100
        timeout: 30
      alphavantage:
        enabled: false
        rate_limit: 5
        timeout: 30

    storage:
      type: "parquet"
      compression: "snappy"
      partitioning: ["date", "symbol"]

  ml-service-config.yaml: |
    models:
      cnn_lstm:
        enabled: true
        model_path: "/models/cnn_lstm"
        batch_size: 32
        device: "cuda"
      rl_agent:
        enabled: true
        model_path: "/models/rl"
        device: "cuda"
      hybrid:
        enabled: true
        model_path: "/models/hybrid"
        device: "cuda"

    inference:
      batch_size: 64
      timeout: 30
      cache_enabled: true
      cache_ttl: 3600

    training:
      enabled: true
      schedule: "0 2 * * *"  # Daily at 2 AM
      gpu_required: true
      max_training_time: 7200  # 2 hours
