apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trading-system-ingress
  namespace: trading-system
  labels:
    app: trading-system
    component: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - api.trading-system.local
        - dashboard.trading-system.local
        - monitoring.trading-system.local
      secretName: trading-system-tls
  rules:
    - host: api.trading-system.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trading-api-service
                port:
                  number: 80
    - host: dashboard.trading-system.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: monitoring.trading-system.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trading-system-internal-ingress
  namespace: trading-system
  labels:
    app: trading-system
    component: internal-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  rules:
    - host: trading-engine.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trading-engine-service
                port:
                  number: 80
    - host: trading-ml.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trading-ml-service
                port:
                  number: 80
    - host: trading-data.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trading-data-pipeline-service
                port:
                  number: 80
    - host: rabbitmq.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trading-rabbitmq-service
                port:
                  number: 15672
