apiVersion: v1
kind: Secret
metadata:
  name: trading-rl-agent-secrets
  namespace: trading-system
  labels:
    app: trading-rl-agent
type: Opaque
data:
  # Trading API credentials
  alpaca-api-key: <base64-encoded-alpaca-api-key>
  alpaca-secret-key: <base64-encoded-alpaca-secret-key>
  alpaca-base-url: <base64-encoded-alpaca-base-url>
  
  # Data provider API keys
  alphavantage-api-key: <base64-encoded-alphavantage-api-key>
  newsapi-key: <base64-encoded-newsapi-key>
  polygon-api-key: <base64-encoded-polygon-api-key>
  
  # Database credentials
  postgres-username: dHJhZGluZ191c2Vy
  postgres-password: <base64-encoded-postgres-password>
  postgres-database: dHJhZGluZ19zeXN0ZW0=
  
  # Redis credentials
  redis-password: <base64-encoded-redis-password>
  
  # RabbitMQ credentials
  rabbitmq-username: dHJhZGluZ191c2Vy
  rabbitmq-password: <base64-encoded-rabbitmq-password>
  
  # JWT signing key
  jwt-secret: <base64-encoded-jwt-secret>
  
  # Monitoring API keys
  prometheus-auth-token: <base64-encoded-prometheus-token>
  grafana-admin-password: <base64-encoded-grafana-password>
  
  # External service API keys
  slack-webhook-url: <base64-encoded-slack-webhook>
  email-smtp-password: <base64-encoded-smtp-password>
  
  # Example of how to encode values:
  # echo -n "your-api-key" | base64
  # echo -n "your-secret-password" | base64
