apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-engine
  namespace: trading-system
  labels:
    app: trading-engine
    component: engine
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: trading-engine
  template:
    metadata:
      labels:
        app: trading-engine
        component: engine
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: trading-engine-service-account
      containers:
        - name: trading-engine
          image: trade-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: http
            - containerPort: 9090
              name: metrics
          env:
            - name: TRADING_RL_AGENT_ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: alpaca-api-key
            - name: TRADING_RL_AGENT_ALPACA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: alpaca-secret-key
            - name: TRADING_RL_AGENT_ALPACA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: alpaca-base-url
            - name: POSTGRES_HOST
              value: "trading-db-service"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: postgres-database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: postgres-password
            - name: REDIS_HOST
              value: "trading-redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: redis-password
            - name: RABBITMQ_HOST
              value: "trading-rabbitmq-service"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: rabbitmq-username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: rabbitmq-password
            - name: ML_SERVICE_URL
              value: "http://trading-ml-service:8002"
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENVIRONMENT
              value: "production"
            - name: ENGINE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["python", "-m", "src.trading_engine.main"]
          args:
            - "--port"
            - "8001"
            - "--workers"
            - "2"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            - name: logs-volume
              mountPath: /app/logs
            - name: data-volume
              mountPath: /app/data
              readOnly: true
            - name: models-volume
              mountPath: /app/models
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: config-volume
          configMap:
            name: trade-agent-config
        - name: logs-volume
          persistentVolumeClaim:
            claimName: trade-agent-logs
        - name: data-volume
          persistentVolumeClaim:
            claimName: trade-agent-data
        - name: models-volume
          persistentVolumeClaim:
            claimName: trade-agent-models
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - trading-engine
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: trading-engine-service
  namespace: trading-system
  labels:
    app: trading-engine
    component: engine
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app: trading-engine
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-engine-service-account
  namespace: trading-system
  labels:
    app: trading-engine
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trading-engine-role
  namespace: trading-system
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trading-engine-role-binding
  namespace: trading-system
subjects:
  - kind: ServiceAccount
    name: trading-engine-service-account
    namespace: trading-system
roleRef:
  kind: Role
  name: trading-engine-role
  apiGroup: rbac.authorization.k8s.io
